### ISSUE TITLE
Is there a way to suppress warnings?

### ISSUE THREAD

**Issue by samwagg** [seancorfield/depstar#28]
I'm getting "clashing jar item" warnings when building an uberjar that I don't have the ability to fix. I'd like to suppress the warnings, but I don't think I can because they are printed via `prn`. Would it be possible to use clojure.logging instead? I'd be happy to submit a PR if so.

**Comment by seancorfield** [comment]
I can add some sort of "silent" option to suppress them but, by default, they should appear as they can highlight problems.

`depstar` uses zero dependencies so that it can package up exactly what is on the classpath (and just exclude itself), so it cannot have any dependencies added (because it might be JAR'ing up a project that has a different version of those dependencies).

**Comment by samwagg** [comment]
Awesome, thanks!

**Comment by seancorfield** [comment]
1.0.next will support `-S` / `--suppress-clash` to suppress just that one warning.

**Comment by aviflax** [comment]
Are there any docs somewhere on how to debug a clash? I’m getting one and I don’t understand where it’s coming from.

<details><summary>Relevant output</summary>

```text
/Users/avi.flax/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar
{:warning "clashing jar item", :path "META-INF/services/com.fasterxml.jackson.core.JsonFactory", :strategy :concat-lines}
```

</details>

**Comment by seancorfield** [comment]
If you're using Jackson, you'll always get `clashing jar item` as they have the `JsonFactory` file in all of their artifacts so that each one independently gets a default factory configured. Clashes don't always need to be "debugged" as they don't always indicate a problem: `depstar` is just letting you know that it found a clash and it resolved it (if it can).

You can enable debug output at three different levels: `-v`, `-vv`, `-vvv`.

**Comment by aviflax** [comment]
Great, thanks!
