### ISSUE TITLE
Generate manifest and AOT compile without pom.xml?

### ISSUE THREAD

**Issue by aviflax** [seancorfield/depstar#30]
I’m wondering whether this might be worth considering as a feature?

I, for one, am interested in using depstar to create an executable uberjar, but I don’t want to learn how to construct a `pom.xml` file, nor a `MANIFEST.MF` file. This seems like the sort of thing that tools like this should be able to do so as to reduce the cognitive load on their users.

What do you think?

**Comment by seancorfield** [comment]
Just run `clojure -Spom` -- an uberjar doesn't really care about group/artifact or version, although those are baked into parts of the JAR file:

```
(! 587)-> mkdir avi
(! 588)-> cd avi
(! 589)-> mkdir -p src/avi
(! 590)-> cat > src/avi/flax.clj
(ns avi.flax 
  (:gen-class))
(defn -main [& args] (println "Hello, World!"))
^D
(! 591)-> clojure -Spom
(! 592)-> clojure -Sdeps '{:deps {seancorfield/depstar {:mvn/version "RELEASE"}}}' -m hf.depstar.uberjar flax.jar -C -m avi.flax
Compiling avi.flax ...
Building uber jar: flax.jar
Processing pom.xml for {avi/avi {:mvn/version "0.1.0"}}
(! 593)-> java -jar flax.jar 
Hello, World!
(! 594)-> 
```

In the above example, I don't even bother creating a `deps.edn` file since I have no dependencies (just Clojure itself). Running `clojure -Spom` creates a minimal `pom.xml` file, which `depstar` can use to build an uberjar, including AOT compilation.

**Comment by aviflax** [comment]
Great, thanks!
